CREATE TABLE IF NOT EXISTS favorites (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(128) NOT NULL,
  isbn VARCHAR(64) NOT NULL,
  title VARCHAR(512),
  authors VARCHAR(512),
  cover_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY ux_user_isbn (user_id, isbn)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS annotations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  isbn VARCHAR(64) UNIQUE NOT NULL,
  title VARCHAR(512),
  authors VARCHAR(512),
  cover_url TEXT,
  annotation TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
